name: Activity Box

on:
  schedule:
    - cron: ${{ secrets.GH_CRON }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: raineydavid/activity-gist@main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ github.repository_owner }} 
          GIST_ID:  ${{ secrets.GH_GIST_ID }} #Github Gist ID gist.github.com
